import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    parsers: 'src/parsers/index.ts',
    schema: 'src/schema/index.ts',
    extensions: 'src/extensions/index.ts',
    'extensions-vue': 'src/extensions-vue/index.ts',
    utils: 'src/utils/index.ts',
    providers: 'src/providers/index.ts',
    editor: 'src/editor/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  clean: true,
  treeshake: true,
  external: [
    'react',
    'react-dom',
    '@tiptap/core',
    '@tiptap/react',
    '@tiptap/vue-3',
    '@tiptap/starter-kit',
    '@tiptap/extension-underline',
    '@tiptap/extension-text-align',
    '@tiptap/extension-table',
    '@tiptap/extension-table-row',
    '@tiptap/extension-table-cell',
    '@tiptap/extension-table-header',
    '@tiptap/extension-link',
    '@tiptap/extension-image',
    '@tiptap/extension-placeholder',
    '@tiptap/extension-task-list',
    '@tiptap/extension-task-item',
    '@tiptap/extension-code-block-lowlight',
    'lowlight',
    'vue',
    'mammoth',
    'mermaid',
    'pdf-parse',
    'word-extractor',
  ],
});
